version: '3.7'
services:
  oun-user:
    container_name: ${CONTAINER_NAME}
    build: .
    ports:
      - 8080:8080
    environment:
      - server.profile=${API_PROFILE}
      - TZ=Asia/Seoul
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
