version: '3.7'

services:
  traefik:
    image: traefik:v3.3
    container_name: simol-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      # SSL 인증서 관련 설정 추가
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # HTTP → HTTPS 리다이렉션
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    labels: 
      - "traefik.enable=true"
      # 인증 미들웨어 정의
      - "traefik.http.middlewares.auth-forward.forwardauth.address=http://simol-user:8080/user/auth"
      - "traefik.http.middlewares.auth-forward.forwardauth.authResponseHeaders=X-User-Id,X-User-Role"
      # CORS 미들웨어 설정
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=Content-Type,Authorization,X-User-Id,X-User-Role"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      # Traefik 대시보드에 SSL 적용
      - "traefik.http.routers.traefik-dashboard.rule=Host(`${DOMAIN_TRAEFIK}`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
    ports:
      - "80:80"
      - "443:443"  # SSL 포트 추가
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt  # 인증서 저장 디렉토리 마운트
    environment:
      - DOMAIN_MAIN=${DOMAIN_MAIN}
      - DOMAIN_TRAEFIK=${DOMAIN_TRAEFIK}
      - ACME_EMAIL=${ACME_EMAIL}
    networks:
      - simol-network    
      
networks:
  simol-network:
    name: simol-network
    driver: bridge