version: '3.7'

services:
  traefik:
    image: traefik:v3.3
    container_name: oun-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    labels: 
      - "traefik.enable=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - oun-network    
      
  oun-user:
    build:
      context: ../oun-user
      dockerfile: Dockerfile
    container_name: oun-user
    environment:
      - TZ=Asia/Seoul
      - SERVER_PROFILE=${SERVER_PROFILE}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    labels:
      - traefik.http.routers.oun-user.rule=PathPrefix(`/user`)
    networks:
      - oun-network
    depends_on:
      - oun-redis
      - oun-mysql

  oun-api:
    build:
      context: ../oun-api
      dockerfile: Dockerfile
    container_name: oun-api
    environment:
      - TZ=Asia/Seoul
      - SERVER_PROFILE=${SERVER_PROFILE}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    labels:
      - traefik.http.routers.oun-api.rule=PathPrefix(`/api`)
    networks:
      - oun-network
    depends_on:
      - oun-user
      - oun-mysql
      - oun-redis

  oun-redis:
    build:
      context: ../redis
      dockerfile: Dockerfile
    container_name: oun-redis
    ports:
      - "6379:6379"
    networks:
      - oun-network
  oun-mysql:
    build:
      context: ../mysql
      dockerfile: Dockerfile
    container_name: oun-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=oun
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - oun-network
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  oun-network:
    name: oun-network
    driver: bridge
