spring:
  application:
    name: oun-user
  profiles:
    active: ${SERVER_PROFILE:local}


jwt:
  secret-key: ${JWT_SECRET_KEY:oun_temp_secret_key_123456789012}
oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

---
# local
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  data:
    redis:
      host: localhost
      port: 6379

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: oun-redis
      port: 6379
  datasource:
    url: jdbc:mysql://oun-mysql:3306/oun?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true