version: '3.7'
services:
  oun-api:
    container_name: oun-api
    build: .
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
      - SERVER_PROFILE=${SERVER_PROFILE}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - oun-network  # 네트워크 연결 추가
    
# oun-user와 redis 네트워크 동일하게 처리
networks:
  oun-network:
    name: oun-network
    driver: bridge
