version: "3.7"
services:
  simol-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simol-mysql
    environment:
      - MYSQL_DATABASE=simol
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - simol-network

volumes:
  mysql-data:

networks:
  simol-network:
    name: simol-network
    driver: bridge
