version: '3.7'
services:
  redis:
    container_name: simol-redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    networks:
      - simol-network
      
networks:
  simol-network:
    name: simol-network
    driver: bridge

